# Hypothesis Testing

Hypothesis Testing with Z-Test
# Z-Testing

In [32]:
# import library
import numpy as np
import pandas as pd
import scipy.stats as st

In [18]:
# import the data which is given in the question 
s_x = 90
p_u = 82
p_std = 20
n = 81
alp = 0.05

In [19]:
# Now apply Z-Testing 
z_cal = (s_x - p_u)/(p_std/np.sqrt(n))
print(f'The Z-Test of the particular data is :',z_cal.round(2))

The Z-Test of the particular data is : 3.6


In [24]:
# Now find the z-table value 
z_table = st.norm.ppf(1 - alp)
print("Z-table value:", z_table.round(2))

Z-table value: 1.64


In [28]:
if z_table < z_cal:
    print('ha is right')
else:
    print('h0 is wright')

ha is right


### Question 2 

In [65]:
# import the data set 
old_design_data = np.array([45.2,42.8,38.9,43.5,41.0,44.6,40.5,42.7,39.8,41.4,44.3,39.7,42.1,40.6,43.0,43.0,42.2,41.5,39.6,44.0,43.1,38.7,43.9,42.0,41.9,42.8,43.7,41.3,40.9,42.5,41.6])
new_design_data = np.array([48.5,48.1,50.2,47.8,48.7,49.9,48.0,50.5,49.8,49.6,48.2,48.9,49.7,50.3,49.4,50.1,48.6,48.3,49.0,50.0,48.4,49.3,49.5,48.8,50.6,50.4,48.1,49.2,50.7,56.4,45.9])

In [66]:
# Now first find the means of both data 
old_mean = old_design_data.mean()
new_mean = new_design_data.mean()

In [56]:
# Now we put the required values 
pop_std = 2.5
n_sp = len(new_design_data)
apl = 0.05


In [58]:
# Now find the z-test
z_cal = (new_mean - old_mean)/(pop_std/np.sqrt(n))
print(f'The Z-Test of the particular data is :',z_cal.round(2))


The Z-Test of the particular data is : 26.49


In [63]:
#Now find the z-table value 
z_table = st.norm.ppf(1 - apl)
print(f"The Z_Table value is :",z_table)

The Z_Table value is : 1.6448536269514722


In [64]:
if z_table < z_cal:
    print('ha is right')
else:
    print('h0 is wright')

ha is right


# T-Test

## Question 1

In [67]:
# Now import the data 
p_u = 150
s_mean = 148
num_sam = 25
std = 5
alp = 0.5

In [73]:
# now find the T-score / T calculate value
T_call = (s_mean - p_u)/(std/np.sqrt(num_sam))
print("The T_test score is :",T_call)

The T_test score is : -2.0


In [72]:
# now find the T table value 
T_table = st.t.ppf(0.05,24)
print("The Table T_test score is :",T_table)

The Table T_test score is : -1.7108820799094282


In [75]:
if T_call < T_table:
    print("ha is right")
else:
    print('h0 is right ')

ha is right


### Question 2 

In [6]:
# import values 
# Here 2 teams value is given 
m_A = 80
m_B = 75
Std_A = 5
Std_B = 6
num_A = 20
num_B = 20
alp = 5#%

In [8]:
# now find T table value 
t_table = st.t.ppf(1-0.025,38)
t_table

np.float64(2.024394163911969)

In [17]:
# now we apply t test 
t_call = (80 - 75)/(np.sqrt((25/20)+ (26/20)).round(2))
t_call

np.float64(3.125)

In [18]:
if t_call > t_table:
    print("ha is right")
else:
    print("ho is right")

ha is right


### Question 3

In [19]:
# Here we have question without mean and std so we have to find from the data set 

In [45]:
before = np.array([50,60,45,65,55,70,40,75,80,65,70,60,50,55,45,75,60,50,65,70])
after = np.array([60,70,55,75,65,80,50,85,90,70,75,65,55,60,50,80,65,55,70,75])

In [59]:
# find mean 
mean_b = np.mean(before)
mean_b

np.float64(60.25)

In [58]:
mean_a = np.mean(after)
mean_a

np.float64(67.5)

In [61]:
# Now find the standard deviation 
std_b = np.std(before).round(2)
std_b

np.float64(11.01)

In [62]:
std_a = np.std(after).round(2)
std_a

np.float64(11.24)

In [50]:
# now calculate the t-table value 
t_table = st.t.ppf(1-0.025,19).round(3)
t_table

np.float64(2.093)

In [63]:
# so before calculate first we arrange all the data 
mean_b = 60.25
mean_a = 67.5
std_b = 11.01
std_a = 11.24
n = 20 

In [71]:
# now calculate the t-test value 
t_call = (mean_a - mean_b)/(np.sqrt(((std_a*std_a)/len(after)) +((std_b*std_b)/len(before)))).round(3)
t_call

np.float64(2.060830017055145)

In [72]:
if t_call < t_table:
    print("ho is right")
else:
    print("ha is right")

ho is right


# Chi-Square Test

In [2]:
# we calculate the chi squre value 

### Question 1 

In [4]:
# load data
ob = np.array([22,17,20,26,22,13])
ex = np.array([20,20,20,20,20,20])

In [21]:
# find chi square table value 
chi_table = st.chi2.ppf(1-0.05,5)
chi_table

np.float64(11.070497693516351)

In [23]:
chi_value = np.sum(np.square(ob-ex)/ex).round(2)
chi_value

np.float64(5.1)

In [24]:
if chi_table > chi_value:
    print("ho die is fair")
else:
    print("ha die is not fair")

ho die is fair


### Question 2 

In [26]:
# given value 
alp = 0.05
df = 3

In [29]:
# now find chi-square table value 
chi_table = st.chi2.ppf(1-0.05,3).round(3)
chi_table

np.float64(7.815)

In [38]:
# data
row1 = np.array([40,45,25,10])
row2 = np.array([35,30,20,30])

In [46]:
# now sum of rows 
sum_r1 = np.sum(row1)
sum_r2 = np.sum(row2)
sum_row =np.array([sum_r1,sum_r2])
sum_row

array([120, 115])

In [44]:
# now sum of column 
sum_c1 = row1 +row2
sum_c1

array([75, 75, 45, 40])

In [55]:
# find excepted value 
exp = []
for i in sum_row:
    for j in sum_c1:
        value = (i*j)/235
        exp.append(value)
exp

[np.float64(38.297872340425535),
 np.float64(38.297872340425535),
 np.float64(22.97872340425532),
 np.float64(20.425531914893618),
 np.float64(36.702127659574465),
 np.float64(36.702127659574465),
 np.float64(22.02127659574468),
 np.float64(19.574468085106382)]

In [57]:
# observation value 
obj = np.array([40,45,25,10,35,30,20,30])
obj

array([40, 45, 25, 10, 35, 30, 20, 30])

In [60]:
# now find chi-square calculated value 
chi_value =np.sum((np.square(obj-exp))/exp)
chi_value

np.float64(13.788747987117553)

In [61]:
if chi_value > chi_table:
    print("Ho (Bothe have association)")
else:
    print("Ha (Both have no association)")

Ho (Bothe have association)
